export default [
  { left: "6.8rem", top: "8.5rem", name: "Calypso's Island" },
  { left: "6.8rem", top: "8.5rem", name: "Calypso's Island" },
  { left: "6.8rem", top: "8.5rem", name: "Calypso's Island" },
  { left: "6.8rem", top: "8.5rem", name: "Calypso's Island" },
  { left: "11rem", top: "6rem", name: "En route to the Phaeaecians" },
  { left: "12.5rem", top: "6.5rem", name: "With the Phaeaecians" },
  { left: "12.5rem", top: "6.5rem", name: "With the Phaeaecians" },
  { left: "12.5rem", top: "6.5rem", name: "With the Phaeaecians" },
  { left: "12.5rem", top: "6.5rem", name: "With the Phaeaecians" },
  { left: "12.5rem", top: "6.5rem", name: "With the Phaeaecians" },
  { left: "12.5rem", top: "6.5rem", name: "With the Phaeaecians" },
  { left: "12.5rem", top: "6.5rem", name: "With the Phaeaecians" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
  { left: "22.2rem", top: "9.9rem", name: "Ithaca" },
];
